### PR TITLE
Make it possible to use macros/attributes outside of the wasmbin

### PR DESCRIPTION
**Pull request by HaronK**
I'm using wasmbin for my own project and trying to its attributes to declare data structures to use them in wasm custom sections.
It appears that some proc_macro's have **crate::** in their **use** declarations and that's blocking me from using them in my project.
This PR make it usable outside of wasmbin too.

### CODE REVIEW

**Comment by RReverser** [comment]
Huh, to be honest I didn't expect someone using those derives externally - they were meant to be more or less internal implementation detail. Out of curiosity, what are the custom sections you're defining? Does it by any chance intersect with https://github.com/GoogleChromeLabs/wasmbin/pull/8?

If those are "standard" custom sections, I'd be happy to add them too.

**Comment by HaronK** [comment]
Hi!
It's a small project that I'm working on with my friend. We are planning to put in a custom section some additional info for the module with connection to some data structures of standard wasm sections.

I found your approach to parse/serialize data in the wasm sections quite nice and useful so decided to try it to declare my own structures.
But it appears that macros are not ready yet to be used outside of wasmbin so I'm trying to fix this now.

Actually this PR doesn't solve my problem completely.

It appears that Wasmbin attribute requires that struct/enum implements Encode and Decode traits for [T] and Vec<T> respectively but your current implementation doesn't allow to do it outside of wasmbin. And when I try to make generic implementation for Encode/[T] and Decode/Vec<T> it conflicts with existing code (i.e. with optimized versions of Encode/[u8] and Decode/Vec<u8>).

So now I'm thinking what to do. It would be hard to fix your crate because of orphan rule problem and missing trait specialization (unless you ok with making your crate nightly).
Alternatively there is [autoref specialization](https://github.com/dtolnay/case-studies/tree/master/autoref-specialization) as substitution of trait specialization or I can add everything in my fork of your crate but I don't like this approach.

Life is not easy :)

**Comment by RReverser** [comment]
> It appears that Wasmbin attribute requires that struct/enum implements Encode and Decode traits for [T] and Vec respectively but your current implementation doesn't allow to do it outside of wasmbin.

Yeah it has to do with Rust's strict rules for implementing traits outside of the main crate. Are you types "countable" by any chance (where Vec<T> is represented by length followed by actual items in binary format)?

If so, perhaps `derive(WasmbinCountable)` would be enough for your use-case.

**Comment by RReverser** [comment]
> Are your types "countable" by any chance (where `Vec<T>` is represented by length followed by actual items in binary format)?

To clarify, I'm referring to "Vectors" in the spec: https://webassembly.github.io/spec/core/binary/conventions.html#vectors

**Comment by HaronK** [comment]
> If so, perhaps `derive(WasmbinCountable)` would be enough for your use-case.

Interesting. Will try today.
And yes, we have vectors.

**Comment by HaronK** [comment]
It compiles now. Cool!

**Pull request closed without merging**
