### PR TITLE
Update crates

### PR DESCRIPTION
**Pull request by Jake-Shadle**
Updates out of date crates and fixes 2 2018 idiom lints.

### CODE REVIEW

**Comment by RReverser** [comment]
Overall looks good but you can't just update `wast` without implementing newer versions of proposals, so going to revert that for now.

**Comment by RReverser** [comment]
Looks like I can't push to this PR. Please revert that part - I'd prefer to update proposals in a separate PR so that we don't have failing CI on master.

**Comment by RReverser** [comment]
I've upgraded wast & implemented newer versions of specs on master now.

**Comment by Jake-Shadle** [comment]
Ahh sorry, forgot about this PR, I'll just close it then.

**Comment by RReverser** [comment]
Well the other crates still need upgrade... But I can do it myself :)

**Comment by RReverser** [comment]
@Jake-Shadle Btw, apologies for not noticing your PRs earlier - I would have responded a lot sooner, but Github helpfully doesn't subscribe you to the repo when you publish it under the org account so I didn't get any notifications...

**Comment by RReverser** [comment]
Upgrade done & published as 0.3.0.

**Comment by Jake-Shadle** [comment]
@RReverser no worries, these things happen!

**Pull request closed without merging**
